travis:
  secure:
    BINSTAR_TOKEN: E1bP4XcxCvV32opHj+xFnIJYLCzgAeP7kbO7jKyr/iNtgvrzZr9BzT6ot0GCSZbRr5qd8z4vTEZpa7sttiCAMHyecFQm5kjZeCHJmuzGf/hUukiVwttLETn6sVwpKXg5lyseeqcs4xz89yF0Gb6UxHc8AbbmY2vyxbcCOzJYcEO6pmdvOPh9qeVKWQf1KFA1zgUzXLqht9ettfYL2ewlOhJou7PiLKIPHZgfTSsfoW1CEPfKB3gxks5Y7thw9CBHoLCWw9pKS3YOVdwBh8+Tcj0zbYqLuNAAJTu9yASoqH5E8gRCCQEOrhd/TSF0RbjvUCi2kkxm21GMUcXBDHFpDNtTi6Yqt5FW7yM1mehLKqONffTMNzguAeRWxIVnizCS3kriOlUUVuWBQpw6W+v7rLUCsS6uDY/5DpI3J+Nczt/Zsk8Quh5v7UlA6+rQSUZOffNrpIPBQAb8tb2v8A3XOAAPZ0sEZbcstHXke7g/Uc6ZOi4VTv9R6gcXINX8ayyWv7ehGVXDtOGAbD7aoyfIk2U3LcTTJPmkh/RpJOYvg8Gg3AqiEXCMRRssJyttZvsjoJbnV4deRxFRPh37tPB/E8yaOQ94pVcD3yUVir629qO7ImezBTDM4+pa21D9RAwtRl8BgZAeUdANYk5Okx89nh6r9MOp0bBRegfXWeDcZFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
